site_name: 'Tock'
site_description: 'Pour construire aisément vos prochains bots'
site_author: 'VSCT'
site_url: 'https://voyages-sncf-technologies.github.io/tock/fr'
repo_name: 'tock'
repo_url: 'https://github.com/voyages-sncf-technologies/tock'
edit_uri: ''
nav:
  - 'Vue d`ensemble': 'index.md'
  - 'Découvrir Tock (guides)': # Guides / Découvrir
      - 'Créer son premier bot': 'getting-started/start-studio.md'
      - 'Configurer Slack': 'getting-started/start-slack.md'
      - 'Configurer Messenger': 'getting-started/start-messenger.md'
      - 'Programmer des parcours': 'getting-started/start-api.md'
      - 'Déployer avec Docker': 'getting-started/start-platform.md'
  - 'Utiliser Tock (manuel)':
      - 'Table des matières': 'user-manual/toc.md'
      - 'Concepts': 'user-manual/concepts.md'
      - 'Tock Studio': 'user-manual/studio.md'
      - 'Tock Bot API': 'user-manual/dev/bot-api.md'
      - 'Tock Bot Framework': 'user-manual/dev/bot-framework.md'
      - 'Les connecteurs': 'user-manual/connectors.md'
      - 'Multilingue / i18n': 'user-manual/i18n.md'
      - 'Installation': 'user-manual/install.md'
  - 'Exemples':
      - 'Usages & utilisateurs': 'examples/users.md'
      - 'Présentations': 'examples/presentations.md'
      - 'Exemples de code': 'examples/samples.md'
  - 'A propos':
      - 'Nous contacter': 'about/community.md'
      - 'Contribuer': 'about/contribute.md'
      - 'Emploi': 'about/jobs.md'
      - 'Remerciements': 'about/acknowledgments.md'


theme:
  name: 'material'
  language: 'fr'
  logo: 'assets/images/logo.svg'
  favicon: 'img/favicon.png'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
copyright: 'Copyright &copy; 2017/2019 VSCT'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/voyages-sncf-technologies/tock'
  search:
    language: 'fr'